In [1]:
import re
import pandas as pd
import numpy as np
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict

In [2]:
def find_subset_indices(A,B):
    len_A = len(A)
    len_B = len(B)

    for i in range(len_A - len_B + 1):
        if A[i:i+len_B] == B: return i, i + len_B - 1

In [3]:
label_names = ['O', 'B-78', 'I-78',
              'B-79', 'I-79',
              'B-89', 'I-89',
              'B-90', 'I-90',
              'B-91', 'I-91',
              'B-95', 'I-95',
              'B-98', 'I-98',
              'B-601', 'I-601',
              'B-862', 'I-862']

In [14]:
def preprocessRecords(csv_path):
    df = pd.read_csv(csv_path)

    # 0
    df = df[~df['cwe'].isin([327,209,311])]

    # 1
    for col in ['cwe', 'flawstart', 'flawend']:
        df[col] = pd.to_numeric(df[col]).astype('Int64')

    # 2
    df['source_flaw'] = None
    for index, row in df.iterrows():
        if not pd.isnull(row['flawstart']):
            df.loc[index, 'source_flaw'] = df.loc[index, 'source'].split('\n')[row['flawstart']-1].strip()
            #df.loc[index, 'source_flaw'] = re.sub(r'/\*(.|\n)*?\*/', '', df.loc[index, 'source_flaw'])
            df.loc[index, 'source_flaw'] = re.sub(r';.*', ';', df.loc[index, 'source_flaw'])
        df.loc[index, 'source'] = re.sub(r'(?://(?![^\r\n]*["\'].*?[^\\]["\']).*)|(\/\*[\s\S]*?\*\/|\/\/.*$)', ' ', row['source'])

    # 3.
    tokenizer = AutoTokenizer.from_pretrained("distilbert/distilbert-base-uncased")

    df['source_tokens'] = None
    df['source_ids'] = None
    df['source_mask'] = None

    for index, row in df.iterrows():
        step = 0
        while True:
            tokenized_input = tokenizer(' '.join(row['source'].splitlines()[step:]), is_split_into_words=False, max_length = 512, padding = 'max_length')
            source_tokens = tokenizer.convert_ids_to_tokens(tokenized_input['input_ids'])
            step += 1
            #if step > 1: print(index, step)
            if len(source_tokens) <= 512: 
                if not pd.isnull(row['flawstart']) and (step >= int(row['flawstart'])): 
                    print("!")
                break
        #tokenized_input = tokenizer(row['source'], is_split_into_words=False, truncation=True, max_length = 512, padding = 'max_length')
        #source_tokens = tokenizer.convert_ids_to_tokens(tokenized_input['input_ids'])
        df.at[index, 'source_tokens'] = source_tokens
        df.at[index, 'source_ids'] = tokenized_input['input_ids']
        df.at[index, 'source_mask'] = tokenized_input['attention_mask']

        ml_bios = np.array([0] * len(source_tokens), dtype='object')
        ml_bios[0] = ml_bios[-1] = -100

        if not pd.isnull(row['flawstart']):
            tokenized_input = tokenizer(row['source_flaw'], is_split_into_words=False, truncation=False)
            flaw_tokens = tokenizer.convert_ids_to_tokens(tokenized_input['input_ids'])[1:-1]
            start_index, end_index = find_subset_indices(source_tokens, flaw_tokens)
            cwe_str = str(row['cwe'])
            beginning = label_names.index("B-"+cwe_str)
            inside = label_names.index("I-"+cwe_str)
            ml_bios[start_index:end_index] = inside
            ml_bios[start_index] = beginning
        df.at[index, 'source_bios'] = ml_bios
        
        if index % 500 == 0: print("Source:",str(index) + "/" + str(len(df)))
        #return

    # 4.
    df['later_tokens'] = None
    df['later_ner'] = None
    
    df['lex_tokens'] = None
    df['lex_ids'] = None
    df['lex_mask'] = None

    for index, row in df.iterrows():
        all_tokens = [' '.join(a.split()[3:]) for a in row['lexed'].splitlines()]
        tokenized_input = tokenizer(all_tokens, is_split_into_words=True, truncation=False, max_length = 512, padding = 'max_length')
        lex_tokens = tokenizer.convert_ids_to_tokens(tokenized_input['input_ids'])
        df.at[index, 'lex_tokens'] = lex_tokens
        df.at[index, 'lex_ids'] = tokenized_input['input_ids']
        df.at[index, 'lex_mask'] = tokenized_input['attention_mask']

        ml_bios = np.array([0] * len(lex_tokens), dtype='object')
        ml_bios[0] = ml_bios[-1] = -100

        later_bios = np.array([0] * len(all_tokens), dtype='object')
        
        if not pd.isnull(row['flawstart']):
            flaw_tokens = [' '.join(a.split()[3:]) for a in row['lexed'].splitlines() if str(row['flawstart']) in a.split()[1]]
            tokenized_input = tokenizer(flaw_tokens, is_split_into_words=True, truncation=False)
            flaw_tokens_t = tokenizer.convert_ids_to_tokens(tokenized_input['input_ids'])[1:-1]
            start_index, end_index = find_subset_indices(lex_tokens, flaw_tokens_t)
            cwe_str = str(row['cwe'])
            beginning = label_names.index("B-"+cwe_str)
            inside = label_names.index("I-"+cwe_str)
            ml_bios[start_index:end_index] = inside
            ml_bios[start_index] = beginning
        
            find_subset_indices(all_tokens, flaw_tokens)
            start_index, end_index = find_subset_indices(all_tokens, flaw_tokens)

        
        
            cwe_str = str(row['cwe'])
            beginning = label_names.index("B-"+cwe_str)
            inside = label_names.index("I-"+cwe_str)
            later_bios[start_index:end_index] = inside
            later_bios[start_index] = beginning
        
        df.at[index, 'lex_bios'] = ml_bios
        df.at[index, 'later_tokens'] = all_tokens
        df.at[index, 'later_ner'] = later_bios

        if index % 500 == 0: print("Lex:",str(index) + "/" + str(len(df)))

    return df

In [15]:
dataset = preprocessRecords('dataset.csv')
dataset = dataset.reset_index()
dataset.to_csv('php-preprocessed.csv', index=False)

Source: 0/42192
Source: 500/42192
Source: 1000/42192
Source: 1500/42192
Source: 2000/42192
Source: 2500/42192
Source: 3000/42192
Source: 3500/42192
Source: 4000/42192
Source: 4500/42192
Source: 5000/42192
Source: 5500/42192
Source: 6000/42192
Source: 6500/42192
Source: 7000/42192
Source: 7500/42192
Source: 8000/42192
Source: 8500/42192
Source: 9000/42192
Source: 9500/42192
Source: 10000/42192
Source: 10500/42192
Source: 11000/42192
Source: 11500/42192
Source: 12000/42192
Source: 12500/42192
Source: 13000/42192
Source: 13500/42192
Source: 14000/42192
Source: 14500/42192
Source: 15000/42192
Source: 15500/42192
Source: 16000/42192
Source: 16500/42192
Source: 17000/42192
Source: 17500/42192
Source: 18000/42192
Source: 18500/42192
Source: 19000/42192
Source: 19500/42192
Source: 20000/42192
Source: 20500/42192
Source: 21000/42192
Source: 21500/42192
Source: 22000/42192
Source: 22500/42192
Source: 23000/42192
Source: 23500/42192
Source: 24000/42192
Source: 24500/42192
Source: 25000/42192
Source: 25500/42192
Source: 26000/42192
Source: 26500/42192
Source: 27000/42192
Source: 27500/42192
Source: 28000/42192
Source: 28500/42192
Source: 29000/42192
Source: 29500/42192
Source: 30000/42192
Source: 30500/42192
Source: 31000/42192
Source: 31500/42192
Source: 32000/42192
Source: 32500/42192
Source: 33000/42192
Source: 33500/42192
Source: 34000/42192
Source: 34500/42192
Source: 35000/42192
Source: 35500/42192
Source: 36000/42192
Source: 36500/42192
Source: 37000/42192
Source: 37500/42192
Source: 38000/42192
Source: 38500/42192
Source: 39000/42192
Source: 39500/42192
Source: 40000/42192
Source: 40500/42192
Source: 41000/42192
Source: 41500/42192
Source: 42000/42192
Lex: 0/42192
Lex: 500/42192
Lex: 1000/42192
Lex: 1500/42192
Lex: 2000/42192
Lex: 2500/42192
Lex: 3000/42192
Lex: 3500/42192
Lex: 4000/42192
Lex: 4500/42192
Lex: 5000/42192
Lex: 5500/42192
Lex: 6000/42192
Lex: 6500/42192
Lex: 7000/42192
Lex: 7500/42192
Lex: 8000/42192
Lex: 8500/42192
Lex: 9000/42192
Lex: 9500/42192
Lex: 10000/42192
Lex: 10500/42192
Lex: 11000/42192
Lex: 11500/42192
Lex: 12000/42192
Lex: 12500/42192
Lex: 13000/42192
Lex: 13500/42192
Lex: 14000/42192
Lex: 14500/42192
Lex: 15000/42192
Lex: 15500/42192
Lex: 16000/42192
Lex: 16500/42192
Lex: 17000/42192
Lex: 17500/42192
Lex: 18000/42192
Lex: 18500/42192
Lex: 19000/42192
Lex: 19500/42192
Lex: 20000/42192
Lex: 20500/42192
Lex: 21000/42192
Lex: 21500/42192
Lex: 22000/42192
Lex: 22500/42192
Lex: 23000/42192
Lex: 23500/42192
Lex: 24000/42192
Lex: 24500/42192
Lex: 25000/42192
Lex: 25500/42192
Lex: 26000/42192
Lex: 26500/42192
Lex: 27000/42192
Lex: 27500/42192
Lex: 28000/42192
Lex: 28500/42192
Lex: 29000/42192
Lex: 29500/42192
Lex: 30000/42192
Lex: 30500/42192
Lex: 31000/42192
Lex: 31500/42192
Lex: 32000/42192
Lex: 32500/42192
Lex: 33000/42192
Lex: 33500/42192
Lex: 34000/42192
Lex: 34500/42192
Lex: 35000/42192
Lex: 35500/42192
Lex: 36000/42192
Lex: 36500/42192
Lex: 37000/42192
Lex: 37500/42192
Lex: 38000/42192
Lex: 38500/42192
Lex: 39000/42192
Lex: 39500/42192
Lex: 40000/42192
Lex: 40500/42192
Lex: 41000/42192
Lex: 41500/42192
Lex: 42000/42192

In [17]:
dataset

,index,source,lexed,state,cwe,flawstart,flawend,source_flaw,source_tokens,source_ids,source_mask,source_bios,later_tokens,later_ner,lex_tokens,lex_ids,lex_mask,lex_bios
0,0,<?php\n \n\n\n\n \n\n\n$tainted = `cat /tmp/ta...,Line 1: T_OPEN_TAG <?php\r\nLine 46: T_VARIABL...,bad,862,51,51,"$query = ""SELECT * FROM student where id=' $ta...","[[CLS], <, ?, php, $, tainted, =, `, cat, /, t...","[101, 1026, 1029, 25718, 1002, 26392, 1027, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $tainted, cat /tmp/tainted.txt, $taint...","[0, 0, 0, 0, 0, 0, 17, 18, 18, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, tainted, cat, /, t, ##mp...","[101, 1026, 1029, 25718, 1002, 26392, 4937, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
1,1,<?php\n \n\n\n\n \n\n\n$tainted = `cat /tmp/ta...,Line 1: T_OPEN_TAG <?php\r\nLine 46: T_VARIABL...,bad,862,51,51,"$query = ""//User[@username='"". $tainted . ""']"";","[[CLS], <, ?, php, $, tainted, =, `, cat, /, t...","[101, 1026, 1029, 25718, 1002, 26392, 1027, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $tainted, cat /tmp/tainted.txt, $taint...","[0, 0, 0, 0, 0, 0, 17, 18, 18, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, tainted, cat, /, t, ##mp...","[101, 1026, 1029, 25718, 1002, 26392, 4937, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
2,2,<?php\n \n\n\n\n \n\n\n$tainted = `cat /tmp/ta...,Line 1: T_OPEN_TAG <?php\r\nLine 46: T_VARIABL...,good,862,<NA>,<NA>,None,"[[CLS], <, ?, php, $, tainted, =, `, cat, /, t...","[101, 1026, 1029, 25718, 1002, 26392, 1027, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $tainted, cat /tmp/tainted.txt, $taint...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, tainted, cat, /, t, ##mp...","[101, 1026, 1029, 25718, 1002, 26392, 4937, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
3,3,<?php\n \n\n\n\n \n\n\n$tainted = `cat /tmp/ta...,Line 1: T_OPEN_TAG <?php\r\nLine 46: T_VARIABL...,bad,862,51,51,"$query = ""SELECT * FROM COURSE WHERE id=?"";","[[CLS], <, ?, php, $, tainted, =, `, cat, /, t...","[101, 1026, 1029, 25718, 1002, 26392, 1027, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $tainted, cat /tmp/tainted.txt, $taint...","[0, 0, 0, 0, 0, 0, 17, 0, 0, 0, 0, 0, 0, 0, 0,...","[[CLS], <, ?, php, $, tainted, cat, /, t, ##mp...","[101, 1026, 1029, 25718, 1002, 26392, 4937, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
4,4,<?php\n \n\n\n\n \n\n\n$tainted = `cat /tmp/ta...,Line 1: T_OPEN_TAG <?php\r\nLine 46: T_VARIABL...,good,862,<NA>,<NA>,None,"[[CLS], <, ?, php, $, tainted, =, `, cat, /, t...","[101, 1026, 1029, 25718, 1002, 26392, 1027, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $tainted, cat /tmp/tainted.txt, $taint...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, tainted, cat, /, t, ##mp...","[101, 1026, 1029, 25718, 1002, 26392, 4937, 10...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42187,42199,<!-- \nUnsafe sample\ninput : get the $_GET['u...,Line 46: T_OPEN_TAG <?php\r\nLine 47: T_VARIAB...,bad,79,56,56,"echo ""window.setInterval('"". $tainted .""');","[[CLS], <, !, -, -, unsafe, sample, input, :, ...","[101, 1026, 999, 1011, 1011, 25135, 7099, 7953...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $array, array, $array, 'safe', $array,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, array, array, $, array, ...","[101, 1026, 1029, 25718, 1002, 9140, 9140, 100...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
42188,42200,<!-- \nUnsafe sample\ninput : get the $_GET['u...,Line 46: T_OPEN_TAG <?php\r\nLine 47: T_VARIAB...,bad,79,56,56,"echo ""body { color :"". $tainted ."" ;","[[CLS], <, !, -, -, unsafe, sample, input, :, ...","[101, 1026, 999, 1011, 1011, 25135, 7099, 7953...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $array, array, $array, 'safe', $array,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, array, array, $, array, ...","[101, 1026, 1029, 25718, 1002, 9140, 9140, 100...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
42189,42201,<!-- \nUnsafe sample\ninput : get the $_GET['u...,Line 46: T_OPEN_TAG <?php\r\nLine 47: T_VARIAB...,bad,79,56,56,"echo ""body { color :\"""". $tainted .""\"" ;","[[CLS], <, !, -, -, unsafe, sample, input, :, ...","[101, 1026, 999, 1011, 1011, 25135, 7099, 7953...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $array, array, $array, 'safe', $array,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, array, array, $, array, ...","[101, 1026, 1029, 25718, 1002, 9140, 9140, 100...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
42190,42202,<!-- \nUnsafe sample\ninput : get the $_GET['u...,Line 46: T_OPEN_TAG <?php\r\nLine 47: T_VARIAB...,bad,79,56,56,"echo ""body { color :\'"". $tainted .""\' ;","[[CLS], <, !, -, -, unsafe, sample, input, :, ...","[101, 1026, 999, 1011, 1011, 25135, 7099, 7953...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $array, array, $array, 'safe', $array,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, array, array, $, array, ...","[101, 1026, 1029, 25718, 1002, 9140, 9140, 100...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."
42191,42203,<!-- \nUnsafe sample\ninput : get the $_GET['u...,Line 46: T_OPEN_TAG <?php\r\nLine 47: T_VARIAB...,bad,79,56,56,"echo ""<span style=\""color :"". tainted .""\"">Hey...","[[CLS], <, !, -, -, unsafe, sample, input, :, ...","[101, 1026, 999, 1011, 1011, 25135, 7099, 7953...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[<?php, $array, array, $array, 'safe', $array,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...","[[CLS], <, ?, php, $, array, array, $, array, ...","[101, 1026, 1029, 25718, 1002, 9140, 9140, 100...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...","[-100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..."